version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'eshop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
  postgresqldb:
    image: postgres
    mem_reservation: 1G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tests@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8889:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: "local:redis:6379"
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - "8890:8081"
    networks:
      - redis_network
    depends_on:
      - redis
volumes:
  db-data:
  pgadmin-data:
  mysql_data:
  redis_data:

networks:
  postgres_network:
    driver: bridge
  mysql_network:
    driver: bridge
  redis_network:
    driver: bridge
