server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
spring:
  servlet:
    multipart:
        max-file-size: 5MB
        max-request-size: 10MB
  profiles:
    include:
      - amazon
      - global-users
      - integration
#      - rest-template
#      - reactive-exchange-webclient
#      - reactive-exchange-interface
      - mock
      - cache-caffeine
  application:
    name: eshop
  main:
    banner-mode: console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 3
  security:
    jwt:
      validity-time-in-minutes: 15
cache:
  products:
    max-size: 1000
    ttl: 1
logging:
  level:
    lt:
      codeacademy:
        spring2025:
          eshop:
            product:
              config: debug
            security:
              filter: trace

company:
  name: E-Shop Company
  address: 123 E-Shop Lane, Commerce City, CA 90210
  color: "#FF0000"
developer:
  names: Jane#Doe, Vardas#Pavardenis, Elon#Musk