spring:
  application:
    name: eshop
  main:
    banner-mode: console
logging:
  level:
    lt:
      codeacademy:
        spring2025:
          eshop:
            product:
              config: debug
