server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
spring:
  profiles:
    include:
      - global-users
  application:
    name: eshop
  main:
    banner-mode: console
  h2:
    console:
      path: /eshop_h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:eshop_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:db/ddl/db-schema.sql
      data-locations: classpath:db/dml/db-data.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 3
logging:
  level:
    lt:
      codeacademy:
        spring2025:
          eshop:
            product:
              config: debug
            security:
              filter: trace