global:
  users:
    - username: admin@eshop.lt
      password: '{noop}admin'
      roles:
        - ADMIN
        - USER
    - username: user@eshop.lt
      password: '{noop}user'
      roles:
        - USER